version: '3'

services:
  flask_app:
      build:
        context: .
      ports:
        - '5000:5000'
      environment:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DB: ${MYSQL_DB}
      depends_on:
        - db